[package]
name = "libp2p-relay"
edition = "2018"
description = "Communications relaying for libp2p"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
bytes = "0.4"
fnv = "1.0"
futures = "0.3.1"
libp2p-core = { version = "0.23.0", path = "../../core" }
libp2p-swarm = { version = "0.23.0", path = "../../swarm" }
log = "0.4"
prost = "0.6.1"
rand = "0.6"
smallvec = "0.6.9"
futures_codec = "0.4"
unsigned-varint = { version = "0.2.1", features = ["codec"] }
void = "1.0"

[build-dependencies]
prost-build = "0.6"

[dev-dependencies]
env_logger = "0.7.1"
libp2p-plaintext = { path = "../plaintext" }
libp2p-yamux = { path = "../../muxers/yamux" }
rand = "0.7.2"
