[package]
name = "libp2p-mdns"
edition = "2018"
version = "0.25.0"
description = "Implementation of the libp2p mDNS discovery method"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-io = "1.2.0"
either = "1.6.1"
data-encoding = "2.3.1"
dns-parser = "0.8.0"
futures = "0.3.8"
if-watch = "0.1.4"
lazy_static = "1.4.0"
libp2p-core = { version = "0.25.0", path = "../../core" }
libp2p-swarm = { version = "0.25.0", path = "../../swarm" }
log = "0.4.11"
net2 = "0.2.35"
rand = "0.7.3"
smallvec = "1.5.0"
void = "1.0.2"
wasm-timer = "0.2.5"

[dev-dependencies]
async-std = "1.7.0"
if-addrs = "0.6.5"
tokio = { version = "0.3.3", default-features = false, features = ["rt", "rt-multi-thread"] }
