[package]
name = "libp2p-tcp"
edition = "2018"
description = "TCP/IP transport protocol for libp2p"
version = "0.22.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-io = "1.1.9"
futures = "0.3.1"
futures-timer = "3.0"
if-addrs = "0.6.4"
ipnet = "2.0.0"
libc = "0.2.79"
libp2p-core = { version = "0.22.0", path = "../../core" }
log = "0.4.1"
socket2 = { version = "0.3.12", features = ["reuseport"] }

[dev-dependencies]
async-std = "1.6.5"
env_logger = "0.7.1"
