[package]
name = "libp2p-autonat"
version = "0.20.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[build-dependencies]
prost-build = "0.6"

[dependencies]
libp2p-core = { version = "0.20.0", path = "../../core" }
libp2p-swarm = { version = "0.20.0", path = "../../swarm" }
prost = "0.6.1"
