[package]
name = "libp2p-autonat"
version = "0.20.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[build-dependencies]
prost-build = "0.6"

[dependencies]
async-trait = "0.1.36"
futures = "0.3.5"
libp2p-core = { version = "0.20.0", path = "../../core" }
libp2p-swarm = { version = "0.20.0", path = "../../swarm" }
libp2p-request-response = { version = "0.1.0", path = "../request-response" }
log = "0.4.11"
prost = "0.6.1"

[dev-dependencies]
async-std = "1.6.2"
netsim-embed = "0.1.0"

[dev-dependencies.libp2p]
default-features = false
features = ["autonat", "noise", "tcp-async-std", "yamux"]
path = "../.."
